[build]
rustflags = [
    # march=native аналог
    "-C", "target-cpu=native",
    # fomit-frame-pointer аналог
    "-C", "force-frame-pointers=no",
    # fstrict-overflow/ffast-math аналог: отключить проверку переполнения
    "-C", "overflow-checks=off",
]
