[package]
name = "bench_rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bench_rust"
path = "bench_rust.rs"

[[bin]]
name = "test_rust"
path = "test_rust.rs"

[[bin]]
name = "bench_rust_simd"
path = "bench_rust_simd.rs"

[dependencies]
base64 = "0.22"
base64-simd = "0.8"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
strip = true
